# Site
title:              Mathias Falci
bio:                'Frontend Developer'
description:        'Frontend Developer'
sub_description:    '#developer #computerscience #jslover'
reading_time:       false
words_per_minute:   200
logo:               'assets/img/perfil.jpg'
#background:         'assets/img/blue-gradients.jpg' 
background:         '' 
tiled_bg:           false   # Set this true if you want to tile your background image, otherwise it will be covered
locale:             pt_BR
url:                http://br468.teste.website/~mathiasf/

# Jekyll
permalink:          /:title/
markdown:           kramdown
highlighter:        rouge
kramdown:
  auto_ids:         true
  footnote_nr:      1
  entity_output:    as_char
  toc_levels:       1..6
  enable_coderay:   false
mathjax:            true
sass:
  sass_dir:         _sass
  style:            compressed

# Comments
disqus_shortname:   Mathias Falci

# Social
# if you don't have any of social below, comment the line.
#google:
  #plus:            #username
  #analytics:
  #verify:
  #ad-client:
  #ad-slot:
#bing-verify:
email:              mathias.falci@gmail.com
#twitter:           username
github-url:         mathiasfc
stackoverflow:      3954447/mathias-falci
linkedin:           mathias-falci-de-castro-9b6778a0
instagram:          mathiasfalci
facebook:           mathiasfalci
#xing:              username
#lastfm:            username
#tumblr:            username
#medium:            '@username'
#pinterest:         username
#foursquare:        username
#steam:              mathiasfcx
#dribbble:          username
#youtube:           username
#youtube-channel:   channel
#soundcloud:        username
#weibo:             username
#flickr:            username
#codepen:           username
#keybase:           username
#xmpp:              username@server.com
#hackernews:        username

# Gems
gems:
  - jekyll-mentions
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-livereload

jekyll-mentions:
    base_url: https://github.com

# Server Config options
livereload: true     # You no longer need to include --livereload

webrick:
  headers:
    Access-Control-Allow-Origin: "*"



# Exclude list
exclude: [README.md, Gemfile, Gemfile.lock, node_modules, gulpfile.js, package.json, _site, src, vendor, CNAME, LICENSE, Rakefile]
